# Generated by Django 2.2.7 on 2020-10-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='oxes',
            name='Oxes_type',
        ),
        migrations.DeleteModel(
            name='Oxestype',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Oxes',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
